//  TRANSACTION ACTIONS
export const ADD_RECURRING_TRANSACTION = 'ADD_RECURRING_TRANSACTION';
export const DELETE_RECURRING_TRANSACTION = 'DELETE_RECURRING_TRANSACTION';
export const LOAD_RECURRING_TRANSACTIONS = 'LOAD_RECURRING_TRANSACTIONS';
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS';
export const ADD_DICTIONARY_ITEM = 'ADD_DICTIONARY_ITEM';
export const LOAD_DICTIONARY = 'LOAD_DICTIONARY';
export const SET_DATE = 'SET_DATE';
export const DELETE_ALL_TRANSACTIONS = 'DELETE_ALL_TRANSACTIONS';
export const FILTER_TRANSACTIONS = 'FILTER_TRANSACTIONS';

// DEBT ACTIONS
export const ADD_DEBT = 'ADD_DEBT';
export const DELETE_DEBT = 'DELETE_DEBT';
export const LOAD_DEBT = 'LOAD_DEBT';
export const CALCULATE_DEBT_SUMMARY = 'CALCULATE_DEBT_SUMMARY';

// STATISTIC ACTIONS
export const LOAD_STATISTICS = 'LOAD_STATISTICS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const SAVE_TRANSACTIONS = 'SAVE_TRANSACTIONS';
export const SAVE_ALL_TRANSACTIONS = 'SAVE_ALL_TRANSACTIONS';
export const CALCULATE_STATISTICS = 'CALCULATE_STATISTICS';

// USER ACTIONS
export const LOAD_USER = 'LOAD_USER';
export const LOGIN = 'LOGIN';

// TRANSACTION/USER ACTIONS
export const LOGOUT = 'LOGOUT';

// PAGE ACTIONS
export const SET_MESSAGE = 'SET_MESSAGE';

// ACCOUNT ACTIONS
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS';

// BILL ACTIONS
export const LOAD_BILLS = 'LOAD_BILLS';
export const ADD_BILL = 'ADD_BILL';
export const UPDATE_BILL = 'UPDATE_BILL';
export const DELETE_BILL = 'DELETE_BILL';

// SUBSCRIPTION ACTIONS
export const LOAD_SUBSCRIPTIONS = 'LOAD_SUBSCRIPTIONS';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const UPDATE_SUBSCRIPTION = 'UPDATE_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';